<div class="container">
	<footer class="footer">
		<div class="pull-right footerRight">
			<a href="/sitemap.html">Sitemap</a>
			<span class="divider-vertical"></span>
			<a href="/terms.html">Terms of Use</a>
			<span class="divider-vertical"></span>
			<a href="/privacy.html">Privacy Policy</a>
			<span class="divider-vertical"></span>
			<a href="/cookie.html">Cookie Usage</a>
		</div>
		<div class="footerLeft">
			<p>
				&copy; 2016
			</p>
		</div>
	</footer>
</div>